[tool.poetry]
name = "europythie"
version = "0.1.0"
description = ""
authors = ["Hugo Porchet <hugo.porchet.belmonte@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
